### ISSUE TITLE
Will linux be supported?

### ISSUE THREAD

**Issue by PhantomRex123** [postcss/postcss#1682]
Currently, postcss doesn't work on linux. Any ways to fix this? or this project wont support linux?

**Comment by ai** [comment]
I, as a creator of PostCSS, use Linux. Of course, we support Linux.

What is the error exactly?

**Comment by PhantomRex123** [comment]
OS: Arch - Hardenend
Installed via NPMv8.1.4
Error:
```zsh
Bento on  master [!?] via ⬢ v17.1.0
[I] ➜ sudo npm install
[sudo] password for ryan:

up to date, audited 79 packages in 2s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Bento on  master [!?] via ⬢ v17.1.0 took 6s
[I] ➜ cat package.json
{
  "dependencies": {
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.1",
    "postcss-cli": "^9.0.2"
  }
}

Bento on  master [!?] via ⬢ v17.1.0
[I] ➜ postcss
zsh: command not found: postcss
```

Another version:
```zsh
Bento on  master [!?] is 📦 v1.2.0 via ⬢ v17.1.0 took 8s
[I] ➜ sudo npm install

changed 62 packages, and audited 141 packages in 18s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Bento on  master [!?] is 📦 v1.2.0 via ⬢ v17.1.0 took 19s
[I] ➜ cat package.json
{
  "name": "bento",
  "version": "1.2.0",
  "description": "🍱 Minimalist, elegant and hackable startpage inspired by the Bento box!",
  "devDependencies": {
    "autoprefixer": "latest",
    "cssnano": "^5.0.11",
    "postcss": "^8.4.1",
    "postcss-cli": "^9.0.2"
  },
  "browserslist": [
    "last 5 versions"
  ],
  "homepage": "https://github.com/migueravila/Bento",
  "author": "Miguel Ávila",
  "license": "ISC"
}

Bento on  master [!?] is 📦 v1.2.0 via ⬢ v17.1.0
[I] ➜ postcss
zsh: command not found: postcss
```

**Comment by ai** [comment]
> `postcss`

Use `npx postcss` or `./node_modules/.bin/postcss`.

Installing npm packages globally is a bad practice. The best way is to explicitly run CLI from `node_modules/.bin` by adding `npx`.

> Cannot find module 'fastq'

`postcss-cli` works on my system (Fedora 35) and on Linux CI with Ubuntu. I didn’t find any popular reports about `fastq` and Linux problems. You need to investigate debug this error in a context of your local environment. Something is broken in `node_modules`.
