### ISSUE TITLE
[8.5.27][Regression] type error in latest release

### ISSUE THREAD

**Issue by AviVahl** [postcss/postcss#2154]
```sh
mkdir postcss-type-error
cd postcss-type-error
npm init -y
npm pkg set type=module
npm i typescript postcss
npx tsc --init --skipLibCheck false
echo "import * as postcss from 'postcss'; console.log(postcss);" > main.ts 
npx tsc --noEmit
```

results in:
```
node_modules/postcss/lib/declaration.d.ts:31:45 - error TS2304: Cannot find name 'NodeProps'.

31   export interface DeclarationProps extends NodeProps {
                                               ~~~~~~~~~

Found 1 error in node_modules/postcss/lib/declaration.d.ts:31
```

FYI @ai 
I believe this regressed in https://github.com/postcss/postcss/pull/2138

**Comment by ai** [comment]
Oops, fixed f8fc2525

**Comment by ai** [comment]
Try 8.5.28

**Comment by AviVahl** [comment]
Thank you for the quick fix. Verified from my end.
