### ISSUE TITLE
 root.markClean is not a function error after updating to v8.4.42

### ISSUE THREAD

**Issue by luiseok** [postcss/postcss#1966]
Hi!

After updating to version 8.4.42, I started encountering the error `TypeError: root.markClean is not a function` when trying to build the project. I reviewed the changes between versions [v8.4.41 and v8.4.42](https://github.com/postcss/postcss/compare/8.4.41...8.4.42#diff-44bcdc44a3fbe763473a0c2319e344bd0e8fd590297a9b3272926ed7deb1adb6R272), and it seems that the code causing the issue was added in `lib/lazy-result.js` at lines 272 and 377. I wanted to ask if this error is occuring only for me, and if there's anything I can check to resolve it besides downgrading the version?

Here is a screenshot of the error that occurred during the build process:
![image](https://github.com/user-attachments/assets/200ee0dd-f149-45af-b7cf-a0dc4466b625)

Additionally, if there's any other information I should provide or if there's anything that doesn't align with the issue guidelines, please let me know. I'd appreciate any assistance!

**Comment by wrannaman** [comment]
Just hit this too

**Comment by ai** [comment]
Can you check you lock file that you are using the same version of PostCSS? Maybe you have a mix of versions?

**Comment by ai** [comment]
I think this change should fix the issue 79ff9800

@nex3 note, that any AST changes could be dangerous (since other plugin could pass AST from other PostCSS version).

**Comment by ai** [comment]
Try 8.4.43 release

**Comment by alexanderbnelson** [comment]
I'm still getting the same error in 8.4.43. Removed and reinstalled packages and lock file and still got the error.

**Comment by romainmenke** [comment]
@alexanderbnelson Can you provide a minimal reproduction or at least a stacktrace?

**Comment by romainmenke** [comment]
Can you provide the output from `npm ls postcss`?

------

(I've also just updated `postcss` in the `csstools` mono repo and didn't get any issues there. We have very extensive coverage of the PostCSS api.)

**Comment by svengau** [comment]
in my case, downgrading to `8.4.41` fixes the issue.

**Comment by cod3blox** [comment]
For me the error still persist with Next.js 14.2.7 and postcss 8.4.43

**Comment by luiseok** [comment]
I was also using Next.js `v14.2.7`, with postcss `v8.4.42`. Upgrading to `v8.4.43` didn't fix the issue. 

postcss.config.js:
```
module.exports = {
    plugins: {
        'postcss-import': {},
        'tailwindcss/nesting': {},
        tailwindcss: {},
        autoprefixer: {},
    },
}
```

result of `pnpm ls postcss`:
```bash
$ pnpm ls postcss
Legend: production dependency, optional only, dev only

<redacted>@0.1.4 /project/path

devDependencies:
postcss 8.4.43
```

Error stacktrace:
```
$ pnpm dev       

> <redacted>@0.1.4 dev /project/path
> next dev

  ▲ Next.js 14.2.7
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 3.1s
 ○ Compiling /_not-found ...
 ⨯ ./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./src/styles/globals.css
TypeError: root.markClean is not a function
Import trace for requested module:
./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./src/styles/globals.css
./src/styles/globals.css
 ⨯ ./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./src/styles/globals.css
TypeError: root.markClean is not a function
Import trace for requested module:
./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[2]!./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[12].use[3]!./src/styles/globals.css
./src/styles/globals.css
```

**Comment by klader-digital** [comment]
I've got the same issue with @roots/sage.
╭ sage [e9d2b6be39030717]                                                                                                                                                                                                                                                                                ./public
│
│ │ Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
│ │ TypeError: root.markClean is not a function
│ │     at LazyResult.sync (node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:377:14)
│ │     at node_modules/tailwindcss/lib/postcss-plugins/nesting/plugin.js:47:39
│ │     at Object.Once (node_modules/tailwindcss/lib/postcss-plugins/nesting/index.js:16:46)
│ │     at LazyResult.runOnRoot (node_modules/postcss/lib/lazy-result.js:327:23)
│ │     at LazyResult.runAsync (node_modules/postcss/lib/lazy-result.js:258:26)
│ │     at async Object.loader (node_modules/postcss-loader/dist/index.js:84:14)
│
│ │ Module build failed (from ../node_modules/postcss-loader/dist/cjs.js):
│ │ TypeError: root.markClean is not a function
│ │     at LazyResult.sync (node_modules/tailwindcss/node_modules/postcss/lib/lazy-result.js:377:14)
│ │     at node_modules/tailwindcss/lib/postcss-plugins/nesting/plugin.js:47:39
│ │     at Object.Once (node_modules/tailwindcss/lib/postcss-plugins/nesting/index.js:16:46)
│ │     at LazyResult.runOnRoot (node_modules/postcss/lib/lazy-result.js:327:23)
│ │     at LazyResult.runAsync (node_modules/postcss/lib/lazy-result.js:258:26)
│ │     at async Object.loader (node_modules/postcss-loader/dist/index.js:84:14)
│
╰ 4 errors

**Comment by ai** [comment]
Another way to fix the issue 3c7cda09

**Comment by ai** [comment]
Try 8.4.44 release

**Comment by AyoCodess** [comment]
i get same error on .44

**Comment by ai** [comment]
@AyoCodess seems like you have older PostCSS somewhere inside your dependencies. `.44` has no `markClean()` calls anymore.

**Comment by sawirricardo** [comment]
in 8.4.44, stuck at trasnforming step...

**Comment by ai** [comment]
@sawirricardo please, give reproduction repo or help with research of this issue https://github.com/postcss/postcss/issues/1967

**Comment by tagliala** [comment]
@sawirricardo I have updates here: https://github.com/postcss/postcss/issues/1967#issuecomment-2328175966
