### ISSUE TITLE
base64 is not a function after upgrade to v6.0.7

### ISSUE THREAD

**Issue by ipelekhan** [postcss/postcss#1052]
We are using ```node.js v4.2.2``` 32-bit on Windows 7. PostCSS is used indirectly as a postcss-loader dependency.

postcss.config.js is
```js
module.exports = context => ({
  parser: false,
  plugins: {
    autoprefixer: {},
    cssnano: context.env === 'production' ? {} : false,
  },
});
```

webpack config is

```
{
  test: /\.less$/,
  use: ExtractTextPlugin.extract({
    fallback: { loader: 'style-loader', options: { sourceMap: true } },
    use: [
      {
        loader: 'css-loader',
        options: { importLoaders: 1, sourceMap: true },
      },
      { loader: 'postcss-loader', options: { sourceMap: true } },
      { loader: 'less-loader', options: { sourceMap: true } },
    ],
  }),
},
```

Error is (company's policy needs me to change paths a little, sorry)
```
ERROR in ./~/css-loader?{"importLoaders":1,"sourceMap":true}!./~/postcss-loader/lib?{"sourceMap":true}!./~/xxxxxx.css
Module build failed: TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at fromBase64 (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\previous-map.js:25:37)
    at PreviousMap.decodeInline (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\previous-map.js:112:20)
    at PreviousMap.loadMap (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\previous-map.js:142:25)
    at new PreviousMap (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\previous-map.js:59:25)
    at new Input (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\input.js:73:19)
    at parse (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\parse.js:21:17)
    at new LazyResult (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:66:24)
    at Processor.process (xxxxxx\node_modules\postcss-loader\node_modules\postcss\lib\processor.js:117:12)
    at xxxxxx\node_modules\postcss-loader\lib\index.js:138:8
 @ ./~/css-loader?{"importLoaders":1,"sourceMap":true}!./~/postcss-loader/lib?{"sourceMap":true}!./~/less-loader/dist?{"sourceMap":true}!./lib/main.less 3:10-211
 @ ./lib/main.less
 @ multi ./lib/main.less ./lib/index.jsx
```
Should I post something else for clarification?

**Comment by michael-ciniawsky** [comment]
`node.js v4.2.2`, there seems to be a bug somewhere in the `node v4.x` line, could you try `node v4@latest` please ?

**Comment by ipelekhan** [comment]
Sorry, but I can't. I'm working at the large bank, there is only one version of node.js across most of the projects, and we will not receive any updates soon. Right now I have done shrink wrap and changed dependency to 6.0.6 and it works fine. Are there any tips on debugging this issue?

**Comment by michael-ciniawsky** [comment]
hmm... just the diff between `v6.0.6...6.0.7` maybe, but there where problems aswell. It will be difficult to fix correctly in `postcss`, since this seems to be in `buffer` shipping with node itself :)

**Comment by ai** [comment]
Seems like here is the explaination https://github.com/postcss/postcss/issues/1019#issuecomment-315973016

But I still don't know, why `Buffer.from(str, 'base64')` doesn’t work on Node.js 4.2.2 :(.

**Comment by michael-ciniawsky** [comment]
https://github.com/nodejs/node/issues/8053

> It’s not undocumented, it’s just inherited from the superclass 

```
Buffer.from === Uint8Array.from
```

Buffer API backport was in `node >= v4.5.0`

**Comment by ai** [comment]
@michael-ciniawsky can we check it by?

```js
if ( Buffer.from && Buffer.from !== Uint8Array.from ) {
  return Buffer.from(str, 'base64')
} else {
  return new Buffer(str)
}
```

**Comment by michael-ciniawsky** [comment]
`instanceof`  maybe? :)

**Comment by ai** [comment]
@michael-ciniawsky `Buffer.from && !(Buffer instanceof Uint8Array)`?

@ipelekhan can you check what `Buffer instanceof Uint8Array` will return on your old Node.js?

**Comment by michael-ciniawsky** [comment]
hmm.. 🤔  if your first snippet works, I think it's the safer solution, I have no deeper knowledge about the exact `Buffer` prototype chain 😥 . Either way needs definitely tests 😛

**Comment by ai** [comment]
@ipelekhan can you also check `Buffer.from !== Uint8Array.from`?

**Comment by ipelekhan** [comment]
Yeah, sure. Here it is:
```bash
$ node
> Buffer instanceof Uint8Array
false
> Buffer.from !== Uint8Array.from
false
>
```

**Comment by michael-ciniawsky** [comment]
```js
// node v8.1.4
console.log(Object.getPrototypeOf(Buffer)) // [Uint8Array]
console.log(Object.getPrototypeOf(Buffer.from)) // [Function]

console.log(Buffer instanceof Uint8Array) // false
console.log(Buffer.from instanceof Uint8Array) // false
 
console.log(Uint8Array.from) // [Function]
=> console.log(Buffer.from !== Uint8Array.from) // true (should work then) <=
```

```js
Buffer.from !== Uint8Array.from ? Buffer.from() : new Buffer()
```

Seems do it, my `instanceof` suggestion is crap 😛

**Comment by ipelekhan** [comment]
Is there anything else I can help resolving this issue?

**Comment by ai** [comment]
Fixed https://github.com/postcss/postcss/commit/dfbe7c8231b6736018caddaa897b51759b0eb6a3

**Comment by ai** [comment]
Released in 6.0.8.

@ipelekhan can you check it?

**Comment by ipelekhan** [comment]
Sorry, can't check right now, already left the office, I'll post an update tomorrow.

**Comment by ipelekhan** [comment]
@ai, I can confirm, now it works. Thank you!
