### ISSUE TITLE
[regression][8.2.1+] JSON.stringify of parsed nodes array fails with "inputs.get is not a function"

### ISSUE THREAD

**Issue by AviVahl** [postcss/postcss#1502]
```js
const postcss = require('postcss');

const root = postcss.parse(`
.cls {
  color: orange;
}`);

JSON.stringify(root.nodes[0].nodes);
```

works with v8.2.0. started throwing since v8.2.1 (v8.2.2 also throws).

when the above is executed, `Declaration.toJSON` throws:
```
TypeError: inputs.get is not a function
    at Declaration.toJSON (/home/avi/projects/postcss-crash/node_modules/postcss/lib/node.js:194:30)
    at JSON.stringify (<anonymous>)
    at Object.<anonymous> (/home/avi/projects/postcss-crash/t.js:8:18)
```

**Comment by AviVahl** [comment]
Possibly regressed by https://github.com/postcss/postcss/pull/1488

**Comment by ai** [comment]
This fix was released in 8.2.3.

**Comment by AviVahl** [comment]
Original issue is fixed on my end. Thanks. :+1: 
I did have to adjust our es5 transpilation (we're using postcss in the browser) to account for spreading of iterables:
`fixed.inputs = [...inputs.keys()].map(input => input.toJSON())`
